[[headers]]

for = "/*"

[headers.values]

Content-Security-Policy = "frame-ancestors urlshortener.asjas.xyz"
Referrer-Policy = "strict-origin"
Strict-Transport-Security = "max-age=31536000"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
proxy_hide_header = "X-Powered-By"

[build.environment]

NODE_VERSION = "12"
NODE_ENV = 'production'
